[build]
  publish = "."
  
[functions]
  directory = "netlify/functions"
  # Increase timeout to 60 seconds for AI analysis
  timeout = "60s"

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200

[build.environment]
  NODE_VERSION = "18"
